name: Publish test Python package

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -m pip install poetry
    - name: Build package
      run: |
        poetry build
    - name: Publish package to TestPyPI
      if: success()
      uses: pypa/gh-action-pypi-publish@release/v1.8
      with:
        repository-url: https://test.pypi.org/legacy/



